[package]
name = "dqlite_sys"
version = "0.0.0"

edition = "2021"
links = "dqlite"

[build-dependencies]
bindgen = { version = "0.69.4", default-features = false }
system-deps = "6.2.2"

[package.metadata.system-deps]
dqlite = "1.16.0"
