name: CI
on:
  - pull_request

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        dqlite:
          - v1.16.3 # first version to support --enable-build-raft
          - v1.16.4 # latest version
    runs-on: ubuntu-latest
    steps:
    - name: install system deps
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install \
          autoconf \
          automake \
          libsqlite3-dev \
          libtool \
          libuv1-dev \
          make \
          pkg-config
    - uses: actions/checkout@v4
      with:
        repository: canonical/dqlite
        ref: ${{ matrix.dqlite }}
        path: dqlite
    - name: install dqlite
      run: |
        cd dqlite
        autoreconf -i
        ./configure --enable-debug --enable-build-raft
        make -j$(nproc)
        sudo make install
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v4
    - uses: KyleMayes/install-llvm-action@v2
      with:
        version: 16
        directory: llvm
    - name: cargo check
      run: cargo check --workspace

